Repository Quaran-Team/client-GalacticBnB, pull requests merged in 2020-10, with the labels that each got.

#14 Feature/covid header
  galacticShort.png
  package-lock.json
  src/app/app-routing/app-routing.module.ts
  src/app/app.module.ts
  src/app/app/search-page/search-page.component.css
  src/app/app/search-page/search-page.component.html
  src/app/app/search-page/search-page.component.spec.ts
  src/app/app/search-page/search-page.component.ts
  src/app/directory/directory.component.html
  src/app/directory/directory.component.spec.ts
  src/app/header/covid/covid.component.css
  src/app/header/covid/covid.component.html
  src/app/header/covid/covid.component.spec.ts
  src/app/header/covid/covid.component.ts
  src/app/logo/logo.component.css
  src/app/logo/logo.component.html
  src/app/logo/logo.component.spec.ts
  src/app/logo/logo.component.ts
  src/assets/img/galacticShort.png
  src/assets/img/issNASAowns.jpg
Labels: enhancement

#23 Feature/morefilters
  src/app/app.module.ts
  src/app/app/search-page/search-page.component.html
  src/app/more-filters/more-filters.component.css
  src/app/more-filters/more-filters.component.html
  src/app/more-filters/more-filters.component.spec.ts
  src/app/more-filters/more-filters.component.ts
Labels: 1 size small

#37 Feature/morefilters buttons
  src/app/app-routing/app-routing.module.ts
  src/app/app.module.ts
  src/app/more-filters/more-filters.component.ts
  src/app/search-page/search-page.component.css
  src/app/search-page/search-page.component.html
  src/app/search-page/search-page.component.spec.ts
  src/app/search-page/search-page.component.ts
Labels: 2 size medium
